name: Daily Repository Update

on:
  schedule:
    # Runs at 04:30 UTC every day
    - cron: '30 4 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  daily-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Update repository for 24f1001956@ds.study.iitm.ac.in
        run: |
          # Create or update daily status file
          echo "Repository update: $(date -u)" > status.txt
          echo "Last automated check: OK" >> status.txt
          
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
      - name: Commit and push changes
        run: |
          git add status.txt
          git commit -m "Daily repository update [skip ci]"
          git push
